version: "3.8"

services:
  client:
    image: frontend-dev
    container_name: client
    build:
      context: ./client
      dockerfile: Dockerfile.dev
    stdin_open: true
    volumes:
      - ./client:/app
      - /app/node_modules
    tty: true
    ports:
      - "3000:3000"
    networks:
      - mern-app
    depends_on:
      - api

  # Express
  api:
    image: backend
    container_name: api
    build:
      context: ./server
      dockerfile: Dockerfile
      target: development
    restart: always
    volumes:
      - ./server:/app
      - ./server/nodemon.json:/app/nodemon.json
      - /app/server/node_modules
    env_file: ./server/.env
    networks:
      - mern-app
    depends_on:
      - mongo
      - redis
    ports:
      - "8000:8000"
    environment:
      - MONGO_USERNAME=${MONGO_USERNAME}
      - MONGO_PASSWORD=${MONGO_PASSWORD}
      - MONGO_DATABASE=${MONGO_DATABASE}
      - REDIS_URL=${REDIS_URL}
      - REDIS_PORT=${REDIS_PORT}
    command: npm run dev

  # MongoDB
  mongo:
    image: mongo
    container_name: mongo-db
    restart: always
    ports:
      - "27017:27017"
    networks:
      - mern-app
    environment:
      - MONGO_INITDB_ROOT_USERNAME=${MONGO_USERNAME}
      - MONGO_INITDB_ROOT_PASSWORD=${MONGO_PASSWORD}
    volumes:
      - mongo-db:/data/db

  # REDIS
  redis:
    container_name: redis
    restart: always
    image: redis
    command: redis-server
    networks:
      - mern-app
    ports:
      - "6379:6379"
    expose:
      - ${REDIS_PORT}
    volumes:
      - redis-data:/data

networks:
  mern-app:
    driver: bridge
  host:
    name: host
    external: true

volumes:
  mongo-db:
  data:
  redis-data:
