version: "3.8"

services:
  nginx:
    restart: always
    ports:
      - "80:80"
  client:
    image: frontend
    container_name: client
    build:
      context: ./client/
      target: production
    stdin_open: true
    tty: true
    ports:
      - "3000:3000"
    networks:
      - mern-app
    depends_on:
      - api

  api:
    image: backend
    container_name: api
    build:
      context: ./server/
      target: production
    restart: unless-stopped
    networks:
      - mern-app
    depends_on:
      - mongo
      - redis
    ports:
      - "8000:800"
    command: node build/server.js

  mongo:
    image: mongo
    container_name: mongo-db
    restart: unless-stopped
    ports:
      - "27017:27017"
    networks:
      - mern-app
    volumes:
      - mongo-db:/data/db

  redis:
    container_name: redis
    restart: unless-stopped
    image: "redis"
    command: redis-server
    networks:
      - mern-app
    ports:
      - "6379:6379"
    expose:
      - 6379

networks:
  mern-app:
    driver: bridge
  host:
    name: host
    external: true

volumes:
  mongo-db:
  data:
