version: "3.8"

services:
  github-finder:
    restart: always
    build:
      context: .
      args:
        NODE_ENV: production
      target: production
    command: node build/server.js

  mongo:
    image: mongo
    container_name: mongo-db
    restart: always
    environment:
      - MONGO_INITDB_ROOT_USERNAME=${MONGO_USER}
      - MONGO_INITDB_ROOT_PASSWORD=${MONGO_PASSWORD}

    volumes:
      - mongo-db:/data/db
