version: "3.8"

services:
  ts-node-docker:
    restart: always
    container_name: ts-node-docker
    build:
      context: .
      args:
        NODE_ENV: development
      dockerfile: Dockerfile
      target: development
    volumes:
      - ./src:/home/node/app/src
      - ./nodemon.json:/home/node/app/nodemon.json
      - /src/node_modules
    environment:
      - PORT=8000
      - MONGO_USER=${MONGO_USER}
      - MONGO_PASSWORD=${MONGO_PASSWORD}
      - REDIS_URL=redis://redis:6379
    depends_on:
      - mongo
      - redis
    ports:
      - "8000:8000"
    command: npm run dev

  mongo:
    image: mongo
    container_name: mongo-db
    restart: always
    environment:
      - MONGO_INITDB_ROOT_USERNAME=${MONGO_USER}
      - MONGO_INITDB_ROOT_PASSWORD=${MONGO_PASSWORD}

    volumes:
      - mongo-db:/data/db

  redis:
    container_name: redis
    restart: always
    image: "redis"
    command: redis-server
    networks:
      - default
    ports:
      - "6379:6379"
    expose:
      - 6379

volumes:
  mongo-db:
  data:
